In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('../../../../Data/raw/nations_data.csv')
input_data=pd.read_csv('../../../Data/cleaned/input_data.csv')

In [3]:
for col in input_data.columns:
    print(col)

tournament_name
Home_Big_Chances_5
Home_Shots_5
Home_Shots_on_Target_5
Home_touches_in_penalty_area_5
Home_big_chances_last_5
Home_final_third_entries_last_5
Home_touches_in_penalty_area_last_5
Home_wins_last_5
Home_goals_last_5
Home_conceded_last_5
Home_gd_last_5
Away_Big_Chances_5
Away_Shots_5
Away_Shots_on_Target_5
Away_touches_in_penalty_area_5
Away_big_chances_last_5
Away_final_third_entries_last_5
Away_touches_in_penalty_area_last_5
Away_wins_last_5
Away_goals_last_5
Away_conceded_last_5
Away_gd_last_5
Home_elo
Away_elo
ELO_diff

In [4]:
data.describe()

,match_id,is_neutral_ground,home_final_score,away_final_score,home_ball_possession,away_ball_possession,home_big_chances,away_big_chances,home_total_shots,away_total_shots,...,home_errors_lead_to_a_shot,away_errors_lead_to_a_shot,home_high_claims,away_high_claims,home_penalty_saves,away_penalty_saves,home_errors_lead_to_a_goal,away_errors_lead_to_a_goal,home_goals_prevented,away_goals_prevented
count,1.306000e+03,1306.0,1306.000000,1306.000000,1215.000000,1215.000000,1090.000000,1090.000000,1212.000000,1212.00000,...,365.000000,365.000000,488.000000,488.000000,30.000000,30.000000,202.000000,202.000000,80.000000,80.000000
mean,1.209325e+07,0.0,1.644717,1.220521,52.288889,47.546502,2.419266,1.877064,13.105611,10.44967,...,0.810959,0.830137,0.772541,1.000000,0.266667,0.733333,0.514851,0.678218,0.146000,0.123250
std,1.906293e+06,0.0,1.620072,1.418134,14.212021,14.184508,2.072912,1.832150,6.614205,5.73355,...,0.867541,0.979836,0.908269,0.946191,0.449776,0.449776,0.557426,0.669462,0.741711,0.822363
min,8.196197e+06,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.370000,-1.670000
25%,1.075256e+07,0.0,0.000000,0.000000,42.000000,37.000000,1.000000,0.000000,8.000000,6.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.250000,0.000000,0.000000,-0.227500,-0.385000
50%,1.218336e+07,0.0,1.000000,1.000000,53.000000,47.000000,2.000000,1.000000,12.000000,10.00000,...,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.120000,0.105000
75%,1.323359e+07,0.0,2.000000,2.000000,63.000000,58.000000,3.000000,3.000000,17.000000,14.00000,...,1.000000,1.000000,1.000000,1.000000,0.750000,1.000000,1.000000,1.000000,0.442500,0.560000
max,1.622323e+07,0.0,11.000000,10.000000,88.000000,86.000000,17.000000,13.000000,42.000000,32.00000,...,6.000000,9.000000,7.000000,6.000000,1.000000,1.000000,2.000000,3.000000,3.000000,2.400000

In [5]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1306 entries, 0 to 1305
Columns: 106 entries, match_id to away_goals_prevented
dtypes: float64(86), int64(4), object(16)
memory usage: 1.1+ MB
None

In [6]:
data.shape

(1306, 106)

In [6]:
for col in data.columns:
    print(col)

match_id
match_date
tournament_name
is_neutral_ground
Home Team
Away Team
home_final_score
away_final_score
home_ball_possession
away_ball_possession
home_big_chances
away_big_chances
home_total_shots
away_total_shots
home_goalkeeper_saves
away_goalkeeper_saves
home_corner_kicks
away_corner_kicks
home_fouls
away_fouls
home_passes
away_passes
home_tackles
away_tackles
home_free_kicks
away_free_kicks
home_yellow_cards
away_yellow_cards
home_shots_on_target
away_shots_on_target
home_hit_woodwork
away_hit_woodwork
home_shots_off_target
away_shots_off_target
home_blocked_shots
away_blocked_shots
home_shots_inside_box
away_shots_inside_box
home_shots_outside_box
away_shots_outside_box
home_big_chances_scored
away_big_chances_scored
home_big_chances_missed
away_big_chances_missed
home_through_balls
away_through_balls
home_fouled_in_final_third
away_fouled_in_final_third
home_offsides
away_offsides
home_accurate_passes
away_accurate_passes
home_throw-ins
away_throw-ins
home_final_third_entries
away_final_third_entries
home_long_balls
away_long_balls
home_crosses
away_crosses
home_duels
away_duels
home_dispossessed
away_dispossessed
home_ground_duels
away_ground_duels
home_aerial_duels
away_aerial_duels
home_dribbles
away_dribbles
home_tackles_won
away_tackles_won
home_total_tackles
away_total_tackles
home_interceptions
away_interceptions
home_recoveries
away_recoveries
home_clearances
away_clearances
home_total_saves
away_total_saves
home_goal_kicks
away_goal_kicks
home_touches_in_penalty_area
away_touches_in_penalty_area
home_final_third_phase
away_final_third_phase
home_big_saves
away_big_saves
home_red_cards
away_red_cards
home_expected_goals
away_expected_goals
home_punches
away_punches
home_errors_lead_to_a_shot
away_errors_lead_to_a_shot
home_high_claims
away_high_claims
home_penalty_saves
away_penalty_saves
home_errors_lead_to_a_goal
away_errors_lead_to_a_goal
home_goals_prevented
away_goals_prevented

In [7]:
data['tournament_name'].unique()

array(['CONCACAF Gold Cup, Group C', 'CONCACAF Gold Cup, Group B',
       'CONCACAF Gold Cup, Knockout stage', 'Euro, Qualification Playoff',
       'UEFA Nations League, League C, Gr. 1',
       'UEFA Nations League, League A, Gr. 1',
       'UEFA Nations League, League C, Gr. 4',
       'UEFA Nations League, League D, Gr. 1',
       'UEFA Nations League, League B, Gr. 4',
       'UEFA Nations League, League C, Gr. 3', 'World Cup Qual. UEFA G',
       'World Cup Qual. UEFA A', 'World Cup Qual. UEFA D',
       'World Cup Qual. UEFA C', 'World Cup Qual. UEFA F',
       'World Cup Qual. UEFA E', 'World Cup Qual. UEFA I',
       'Int. Friendly Games',
       'World Cup Qualification, AFC, Round 2, Group A',
       'World Cup Qualification, AFC, Round 2, Group B', 'Euro, Group A',
       'Euro, Group B', 'World Cup Qualification, AFC, Round 2, Group H',
       'Euro, Group C', 'Euro, Group D', 'Euro, Group F', 'Euro, Group E',
       'CONMEBOL Copa América, Group A', 'Euro, Knockout stage',
       'CONMEBOL Copa América, Knockout stage', 'World Cup Qual. UEFA H',
       'World Cup Qualification, AFC, Round 3, Group A',
       'World Cup Qualification, AFC, Round 3, Group B',
       'World Cup Qual. UEFA J', 'World Cup Qualification, CONMEBOL',
       'UEFA Nations League, Finals', 'Africa Cup of Nations, Group A',
       'Africa Cup of Nations, Group D',
       'Africa Cup of Nations, Knockout stage',
       'World Cup Qual. UEFA Playoffs', 'World Cup Qual. CAF, Playoffs',
       'Finalissima', 'UEFA Nations League, League A, Gr. 2',
       'UEFA Nations League, League A, Gr. 4',
       'Africa Cup of Nations, Qualification, Group H',
       'UEFA Nations League, League A, Gr. 3',
       'Africa Cup of Nations, Qualification, Group I',
       'Africa Cup of Nations, Qualification, Group D',
       'AFC Asian Cup, Qualification Group C',
       'Africa Cup of Nations, Qualification, Group C',
       'EAFF E-1 Football Championship',
       'African Nations Championship, Group B',
       'African Nations Championship, Group C',
       'African Nations Championship, Knockout stage',
       'Africa Cup of Nations, Qualification, Group G',
       'Africa Cup of Nations, Qualification, Group L',
       'CONCACAF Nations League, League B, Group B',
       'CONCACAF Gold Cup, Preliminary Round',
       'Euro, Qualification Group F', 'Euro, Qualification Group D',
       'Euro, Qualification Group I', 'Euro, Qualification Group E',
       'Euro, Qualification Group J', 'Euro, Qualification Group H',
       'CONCACAF Nations League, League A, Group A',
       'CONCACAF Nations League, League B, Group C',
       'CONCACAF Nations League, League A, Group B',
       'Euro, Qualification Group G',
       'FIFA World Cup, Qualification CAF, Group F',
       'AFC Asian Cup, Group A', 'AFC Asian Cup, Group B',
       'Africa Cup of Nations, Group B', 'Africa Cup of Nations, Group C',
       'AFC Asian Cup, Group C', 'AFC Asian Cup, Knockout stage',
       'World Cup Qualification, AFC, Round 2, Group I',
       'World Cup Qualification, AFC, Round 2, Group C',
       'World Cup Qualification, AFC, Round 2, Group E',
       'World Cup Qualification, CONCACAF 2nd round, Group A',
       'World Cup Qualification, CONCACAF 2nd round, Group C',
       'World Cup Qualification, AFC, Round 2, Group F',
       'FIFA World Cup, Qualification CAF, Group E',
       'FIFA World Cup, Qualification CAF, Group D', 'Baltic Cup',
       'CONMEBOL Copa América, Group B', 'CONMEBOL Copa América, Group C',
       'CONMEBOL Copa América, Group D',
       'Africa Cup of Nations, Qualification, Group A',
       'World Cup Qualification, AFC, Round 3, Gr. C',
       'UEFA Nations League, League B, Gr. 3',
       'Africa Cup of Nations, Qualification, Group B',
       'CONCACAF Nations League, League B, Group D',
       'UEFA Nations League, League B, Gr. 1',
       'UEFA Nations League, League B, Gr. 2',
       'Africa Cup of Nations, Qualification, Group J',
       'UEFA Nations League, League D, Gr. 2',
       'Africa Cup of Nations, Qualification, Group F',
       'Gulf Cup, Group B',
       'UEFA Nations League, Promotion/Relegation Play-offs',
       'FIFA World Cup, Qualification CAF, Group B',
       'World Cup Qual. UEFA K',
       'FIFA World Cup, Qualification CAF, Group A',
       'World Cup Qual. UEFA L', 'AFC Asian Cup, Qualification Group E',
       'AFC Asian Cup, Qualification Group B', 'COSAFA Cup, Group D',
       'CONCACAF Gold Cup, Group D',
       'African Nations Championship, Group A',
       'African Nations Championship, Group D',
       'CAFA Nations Cup, Group B', 'CAFA Nations Cup, Group A',
       'World Cup Qual. CONCACAF Group B',
       'World Cup Qual. CONCACAF Group C',
       'CAFA Nations Cup, Knockout round',
       'World Cup Qualification, AFC, Round 4, Gr. B',
       'World Cup Qualification, AFC, Round 5', 'World Cup Qual. CAF',
       'Arab Cup, Group A', 'Arab Cup, Group C', 'Arab Cup, Group D',
       'Arab Cup, Knockout Stage', 'Africa Cup of Nations, Group E',
       'Africa Cup of Nations, Group F',
       'FIFA World Cup Qual, Inter-Confed. Playoffs',
       'FIFA Series, New Zealand ', 'FIFA Series, Australia',
       'FIFA Series, Uzbekistan '], dtype=object)

In [8]:
len(data['Home Team'].unique())

179

In [10]:
data[data['Home Team'].str.endswith("rde")]

,match_id,match_date,tournament_name,is_neutral_ground,Home Team,Away Team,home_final_score,away_final_score,home_ball_possession,away_ball_possession,...,home_errors_lead_to_a_shot,away_errors_lead_to_a_shot,home_high_claims,away_high_claims,home_penalty_saves,away_penalty_saves,home_errors_lead_to_a_goal,away_errors_lead_to_a_goal,home_goals_prevented,away_goals_prevented
208,9737692,2022-01-13 19:00:00,"Africa Cup of Nations, Group A",0,Cabo Verde,Burkina Faso,0,1,56.0,44.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
210,9736788,2022-01-17 16:00:00,"Africa Cup of Nations, Group A",0,Cabo Verde,Cameroon,1,1,36.0,64.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
409,11761888,2024-01-19 14:00:00,"Africa Cup of Nations, Group B",0,Cabo Verde,Mozambique,3,0,49.0,51.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
413,11761898,2024-01-22 20:00:00,"Africa Cup of Nations, Group B",0,Cabo Verde,Egypt,2,2,47.0,53.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
420,11940727,2024-01-29 17:00:00,"Africa Cup of Nations, Knockout stage",0,Cabo Verde,Mauritania,1,0,69.0,31.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
426,11940748,2024-02-03 20:00:00,"Africa Cup of Nations, Knockout stage",0,Cabo Verde,South Africa,1,2,51.0,49.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
455,12162619,2024-03-25 19:00:00,Int. Friendly Games,0,Cabo Verde,Equatorial Guinea,1,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
528,12183442,2024-06-11 16:00:00,"FIFA World Cup, Qualification CAF, Group D",0,Cabo Verde,Libya,1,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
659,12526719,2024-09-10 19:00:00,"Africa Cup of Nations, Qualification, Group C",0,Cabo Verde,Mauritania,2,0,53.0,47.0,...,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
670,12526713,2024-10-10 16:00:00,"Africa Cup of Nations, Qualification, Group C",0,Cabo Verde,Botswana,0,1,77.0,23.0,...,NaN,NaN,0.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN
752,12526773,2024-11-15 16:00:00,"Africa Cup of Nations, Qualification, Group C",0,Cabo Verde,Egypt,1,1,41.0,59.0,...,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
814,12183480,2025-03-20 16:00:00,"FIFA World Cup, Qualification CAF, Group D",0,Cabo Verde,Mauritius,1,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1015,12183498,2025-09-09 16:00:00,"FIFA World Cup, Qualification CAF, Group D",0,Cabo Verde,Cameroon,1,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1085,12183390,2025-10-13 16:00:00,"FIFA World Cup, Qualification CAF, Group D",0,Cabo Verde,Eswatini,3,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1245,15400664,2026-03-30 03:00:00,"FIFA Series, New Zealand",0,Cabo Verde,Finland,5,3,52.0,48.0,...,1.0,0.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
teams=set()
for team in data['Home Team']:
    teams.add(team)
for i in teams:
    print(i)

Tajikistan
Israel
Lebanon
China
Basque Country
Latvia
Belarus
Japan
Curaçao
Saint Lucia
Zimbabwe
Moldova
Syria
Yemen
Estonia
Libya
Northern Ireland
Andorra
Australia
France
Indonesia
Dominica
Burundi
San Marino
Norway
Turkmenistan
Faroe Islands
Bangladesh
Senegal
Cameroon
Iran
Ghana
Armenia
Saudi Arabia
Bermuda
Sweden
North Korea
Maldives
French Guiana
Uruguay
Scotland
Myanmar
Hungary
Slovenia
Seychelles
Cabo Verde
Comoros
Ireland
Nepal
DR Congo
Chile
Congo Republic
Palestine
Argentina
Pakistan
South Africa
Ecuador
Central African Republic
Luxembourg
Sudan
Mexico
Denmark
Austria
Togo
Albania
Botswana
Angola
Hong Kong
Gibraltar
Malawi
Gabon
Russia
Madagascar
Haiti
Colombia
Guam
Iraq
Bahrain
Barbados
Mauritania
Sierra Leone
Peru
Romania
Ukraine
Kazakhstan
Canada
Montenegro
Georgia
Burkina Faso
Saint Vincent and the Grenadines
Antigua and Barbuda
Grenada
Morocco
Zambia
Cyprus
Equatorial Guinea
Iceland
Egypt
USA
Suriname
Kosovo
Wales
Slovakia
Kuwait
Mozambique
Netherlands
Cuba
Brazil
Belgium
Nigeria
Guinea
Germany
Czechia
Venezuela
Malta
Ethiopia
Vietnam
India
Türkiye
Afghanistan
Lesotho
Eswatini
Aruba
Guatemala
Costa Rica
Benin
North Macedonia
Belize
Oman
Croatia
Azerbaijan
Bolivia
Puerto Rico
Qatar
Niger
Uganda
Thailand
Portugal
Mauritius
Tunisia
Gambia
Trinidad and Tobago
Honduras
Bosnia & Herzegovina
Martinique
Namibia
Liechtenstein
Brunei Darussalam
United Arab Emirates
England
Dominican Republic
Côte d'Ivoire
Sint Maarten
Bulgaria
Finland
Algeria
Chad
South Sudan
Lithuania
Switzerland
Tanzania
New Zealand
Bhutan
South Korea
Jamaica
Kyrgyzstan
Italy
Saint Martin
Paraguay
Serbia
Djibouti
Jordan
Greece
Nicaragua
Kenya
Spain
Poland
Mali
Uzbekistan

In [11]:
data.head()

,match_id,match_date,tournament_name,is_neutral_ground,Home Team,Away Team,home_final_score,away_final_score,home_ball_possession,away_ball_possession,...,home_errors_lead_to_a_shot,away_errors_lead_to_a_shot,home_high_claims,away_high_claims,home_penalty_saves,away_penalty_saves,home_errors_lead_to_a_goal,away_errors_lead_to_a_goal,home_goals_prevented,away_goals_prevented
0,8196197,2019-06-17 23:00:00,"CONCACAF Gold Cup, Group C",0,Curaçao,El Salvador,0,1,59.0,41.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,8196202,2019-06-20 23:00:00,"CONCACAF Gold Cup, Group B",0,Nicaragua,Haiti,0,2,68.0,32.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,8196205,2019-06-22 01:30:00,"CONCACAF Gold Cup, Group C",0,Honduras,Curaçao,0,1,63.0,37.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,8196827,2019-06-25 01:00:00,"CONCACAF Gold Cup, Group B",0,Haiti,Costa Rica,2,1,40.0,60.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,8196207,2019-06-26 00:00:00,"CONCACAF Gold Cup, Group C",0,Jamaica,Curaçao,1,1,40.0,60.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
import pandas as pd

data=pd.read_csv('../../../Data/raw/nations_data.csv')

In [13]:
import sys
import os
sys.path.append(os.path.abspath('../../..'))

import src.ETL.Transform.feature_engineering as edit

data,stats,elos=edit.preprocessing(data)

In [18]:
stats.to_csv('../../../Data/cleaned/teams_data.csv')

In [19]:
for col in stats.columns:
    print (col)

Team
Date
Big Chances
Total Shots
Shots on Target
Big Chances Scored
Final Third Entries
Touches in Penalty Area
Final Result
Wins
Draws
Wins_Last_5
Goals_Last_5
Conceded_Last_5
GD_Last_5
Big Chances EMA 5
Total Shots EMA 5
Shots on Target EMA 5
Big Chances Scored last 5
Final Third Entries last 5
Touches in Penalty Area EMA 5
Touches in Penalty Area last 5

In [20]:
data.head(len(data))

,tournament_name,Home Team,Away Team,Final Result,Home_Big_Chances_5,Home_Shots_5,Home_Shots_on_Target_5,Home_touches_in_penalty_area_5,Home_big_chances_last_5,Home_final_third_entries_last_5,...,Away_big_chances_last_5,Away_final_third_entries_last_5,Away_touches_in_penalty_area_last_5,Away_wins_last_5,Away_goals_last_5,Away_conceded_last_5,Away_gd_last_5,Home_elo,Away_elo,ELO_diff
0,Friendlies & Minor,Haiti,Costa Rica,H,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1510.000000,1500.000000,10.000000
1,Nations League,Azerbaijan,Montenegro,D,NaN,NaN,NaN,NaN,0.000000,104.000000,...,1.000000,44.000000,NaN,NaN,NaN,NaN,NaN,1490.287744,1510.000000,-19.712256
2,Nations League,Ireland,Bulgaria,D,NaN,NaN,NaN,NaN,NaN,NaN,...,1.000000,57.000000,NaN,NaN,NaN,NaN,NaN,1500.000000,1490.000000,10.000000
3,Qualifiers,Finland,Bosnia & Herzegovina,D,NaN,NaN,NaN,NaN,1.000000,51.000000,...,0.864198,101.543210,NaN,0.0,5.0,13.0,-8.0,1510.000000,1461.947084,48.052916
4,Qualifiers,San Marino,Hungary,A,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1500.000000,1500.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
801,Friendlies & Minor,Croatia,Slovenia,H,2.8,13.2,3.6,26.6,2.746644,149.747070,...,1.911328,114.412680,40.535437,2.0,6.0,3.0,3.0,1594.905212,1517.146073,77.759139
802,Friendlies & Minor,Ecuador,Guatemala,H,2.0,12.6,3.8,20.8,3.469199,164.038912,...,0.000000,64.666667,5.000000,NaN,NaN,NaN,NaN,1558.897718,1484.358946,74.538771
803,Friendlies & Minor,Colombia,Jordan,H,1.8,15.8,6.4,26.0,5.214140,194.255598,...,2.421125,113.969822,49.443073,2.0,5.0,2.0,3.0,1566.968011,1510.286130,56.681881
804,Friendlies & Minor,Netherlands,Uzbekistan,H,3.4,12.2,4.6,27.2,2.945297,188.977223,...,1.255596,129.670657,51.464754,4.0,14.0,10.0,4.0,1603.660697,1604.801599,-1.140902
805,Friendlies & Minor,France,Northern Ireland,H,3.8,15.6,5.6,36.0,3.897811,167.711418,...,2.260580,143.507849,47.445816,2.0,9.0,5.0,4.0,1626.754099,1490.791612,135.962487

In [21]:
for col in data.columns:
    print (col)

tournament_name
Home Team
Away Team
Final Result
Home_Big_Chances_5
Home_Shots_5
Home_Shots_on_Target_5
Home_touches_in_penalty_area_5
Home_big_chances_last_5
Home_final_third_entries_last_5
Home_touches_in_penalty_area_last_5
Home_wins_last_5
Home_goals_last_5
Home_conceded_last_5
Home_gd_last_5
Away_Big_Chances_5
Away_Shots_5
Away_Shots_on_Target_5
Away_touches_in_penalty_area_5
Away_big_chances_last_5
Away_final_third_entries_last_5
Away_touches_in_penalty_area_last_5
Away_wins_last_5
Away_goals_last_5
Away_conceded_last_5
Away_gd_last_5
Home_elo
Away_elo
ELO_diff

In [ ]:
data.shape

In [ ]:
data.describe()

In [ ]:
data_data=pd.DataFrame(data.describe())
data_data.to_csv('../../../Data/cleaned/data_describe.csv',index=False)

In [ ]:
data[
    [
    'Home_Shots_5',
    'Home_Shots_on_Target_5',
    'Home_big_chances_last_5',
    'Home_final_third_entries_last_5',
    'Home_touches_in_penalty_area_last_5',
    'Home_wins_last_5',
    'Home_goals_last_5',
    'Home_conceded_last_5',
    'Home_gd_last_5',
    'Away_Shots_5',
    'Away_Shots_on_Target_5',
    'Away_big_chances_last_5',
    'Away_final_third_entries_last_5',
    'Away_touches_in_penalty_area_last_5',
    'Away_wins_last_5',
    'Away_goals_last_5',
    'Away_conceded_last_5',
    'Away_gd_last_5',
    'Home_elo',
    'Away_elo',
    'ELO_diff'
     ]
].corr()

In [ ]:
data.info()

In [ ]:
data.dtypes

In [ ]:
stats=pd.read_csv('../../../Da')